 // Source code is unavailable, and was generated by the Fernflower decompiler.
public class jav5 {
   public static void main(String[] var0) {
      System.out.println("=== STRUCTURE if SIMPLE ===");
      byte var1 = 20;
      if (var1 >= 18) {
         System.out.println("Vous \u00eates majeur.");
      }

      if (var1 < 18) {
         System.out.println("Vous \u00eates mineur.");
      }

      boolean var2 = true;
      if (var1 >= 18 && var2) {
         System.out.println("Vous pouvez conduire.");
      }

      System.out.println();
      System.out.println("=== STRUCTURE if-else ===");
      if (var1 >= 18) {
         System.out.println("Majeur");
      } else {
         System.out.println("Mineur");
      }

      byte var3 = 7;
      if (var3 % 2 == 0) {
         System.out.println(var3 + " est pair.");
      } else {
         System.out.println(var3 + " est impair.");
      }

      System.out.println();
      System.out.println("=== STRUCTURE if-else if-else ===");
      byte var4 = 75;
      if (var4 >= 90) {
         System.out.println("Excellent");
      } else if (var4 >= 80) {
         System.out.println("Tr\u00e8s bien");
      } else if (var4 >= 70) {
         System.out.println("Bien");
      } else if (var4 >= 60) {
         System.out.println("Assez bien");
      } else if (var4 >= 50) {
         System.out.println("Passable");
      } else {
         System.out.println("\u00c9chec");
      }

      System.out.println();
      System.out.println("=== CONDITIONS IMBRIQU\u00c9ES ===");
      boolean var5 = true;
      boolean var6 = false;
      if (var5) {
         if (var6) {
            System.out.println("Acc\u00e8s administrateur");
         } else {
            System.out.println("Acc\u00e8s utilisateur");
         }
      } else {
         System.out.println("Veuillez vous connecter");
      }

      if (var5 && var6) {
         System.out.println("Acc\u00e8s administrateur");
      } else if (var5 && !var6) {
         System.out.println("Acc\u00e8s utilisateur");
      } else {
         System.out.println("Veuillez vous connecter");
      }

      System.out.println();
      System.out.println("=== STRUCTURE switch CLASSIQUE ===");
      byte var7 = 3;
      switch(var7) {
      case 1:
         System.out.println("Lundi");
         break;
      case 2:
         System.out.println("Mardi");
         break;
      case 3:
         System.out.println("Mercredi");
         break;
      case 4:
         System.out.println("Jeudi");
         break;
      case 5:
         System.out.println("Vendredi");
         break;
      case 6:
         System.out.println("Samedi");
         break;
      case 7:
         System.out.println("Dimanche");
         break;
      default:
         System.out.println("Jour invalide");
      }

      switch(var7) {
      case 1:
      case 2:
      case 3:
      case 4:
      case 5:
         System.out.println("Jour ouvr\u00e9");
         break;
      case 6:
      case 7:
         System.out.println("Week-end !");
         break;
      default:
         System.out.println("Jour invalide");
      }

      System.out.println();
      System.out.println("=== STRUCTURE switch MODERNE ===");
      switch(var7) {
      case 1:
         System.out.println("Lundi");
         break;
      case 2:
         System.out.println("Mardi");
         break;
      case 3:
         System.out.println("Mercredi");
         break;
      case 4:
         System.out.println("Jeudi");
         break;
      case 5:
         System.out.println("Vendredi");
         break;
      case 6:
         System.out.println("Samedi");
         break;
      case 7:
         System.out.println("Dimanche");
         break;
      default:
         System.out.println("Jour invalide");
      }

      String var10000;
      switch(var7) {
      case 1:
         var10000 = "Lundi";
         break;
      case 2:
         var10000 = "Mardi";
         break;
      case 3:
         var10000 = "Mercredi";
         break;
      case 4:
         var10000 = "Jeudi";
         break;
      case 5:
         var10000 = "Vendredi";
         break;
      case 6:
         var10000 = "Samedi";
         break;
      case 7:
         var10000 = "Dimanche";
         break;
      default:
         var10000 = "Inconnu";
      }

      String var8 = var10000;
      System.out.println("Jour : " + var8);
      switch(var7) {
      case 1:
      case 2:
      case 3:
      case 4:
      case 5:
         var10000 = "Jour ouvr\u00e9";
         break;
      case 6:
      case 7:
         var10000 = "Week-end";
         break;
      default:
         var10000 = "Invalide";
      }

      String var9 = var10000;
      System.out.println("Type : " + var9);
      System.out.println();
      System.out.println("=== OP\u00c9RATEUR TERNIAIRE ===");
      String var10 = var1 >= 18 ? "Majeur" : "Mineur";
      System.out.println("Statut : " + var10);
      byte var11 = 10;
      byte var12 = 5;
      byte var13 = var11 > var12 ? var11 : var12;
      System.out.println("Maximum : " + var13);
      System.out.println();
      System.out.println("=== EXEMPLE PRATIQUE : SYST\u00c8ME DE NOTES ===");
      byte var14 = 85;
      String var15 = "Alice";
      System.out.println("\u00c9tudiant : " + var15);
      System.out.println("Note : " + var14 + "/100");
      String var16;
      if (var14 >= 90) {
         var16 = "Excellent";
      } else if (var14 >= 80) {
         var16 = "Tr\u00e8s bien";
      } else if (var14 >= 70) {
         var16 = "Bien";
      } else if (var14 >= 60) {
         var16 = "Assez bien";
      } else if (var14 >= 50) {
         var16 = "Passable";
      } else {
         var16 = "\u00c9chec";
      }

      String var17 = var14 >= 50 ? "ADMIS" : "AJOURN\u00c9";
      System.out.println("Mention : " + var16);
      System.out.println("R\u00e9sultat : " + var17);
      System.out.println();
      System.out.println("=== EXEMPLE PRATIQUE : CALCULATRICE ===");
      double var18 = 15.5D;
      double var20 = 4.0D;
      byte var22 = 3;
      System.out.printf("Nombres : %.2f et %.2f%n", var18, var20);
      switch(var22) {
      case 1:
         System.out.println("Op\u00e9ration : Addition");
         System.out.printf("R\u00e9sultat : %.2f%n", var18 + var20);
         break;
      case 2:
         System.out.println("Op\u00e9ration : Soustraction");
         System.out.printf("R\u00e9sultat : %.2f%n", var18 - var20);
         break;
      case 3:
         System.out.println("Op\u00e9ration : Multiplication");
         System.out.printf("R\u00e9sultat : %.2f%n", var18 * var20);
         break;
      case 4:
         System.out.println("Op\u00e9ration : Division");
         if (var20 != 0.0D) {
            System.out.printf("R\u00e9sultat : %.2f%n", var18 / var20);
         } else {
            System.out.println("Erreur : Division par z\u00e9ro !");
         }
         break;
      default:
         System.out.println("Op\u00e9ration invalide");
      }

      System.out.println();
      System.out.println("\u2705 Jour 5 termin\u00e9 !");
      System.out.println("Prochaine \u00e9tape : Boucles (for, while, do-while)");
   }
}
